version: "2.2"
services:
  iris:
    image: intersystemsdc/irishealth-community:preview
    command: --check-caps false
    restart: always
    cpuset: "0-1"
    build:
      context: iris
      dockerfile: Dockerfile
      args:
        IRIS_IMAGE: intersystemsdc/irishealth-community:preview
    ports:
      - 52773:52773
      - 1973:1972

  jaeger:
    image: jaegertracing/all-in-one:1.51
    restart: unless-stopped
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Collector HTTP (/api/traces)
      - "14250:14250"  # gRPC Collector
      - "6831:6831/udp"  # Agent (optional)
      - "9411:9411"      # Zipkin (optional)
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
